In [1]:
import torch

In [2]:
# Construc a 5*3 matrix, unintialized:
x = torch.empty(5,3)
print(x)

tensor([[9.1837e-39, 4.6837e-39, 9.9184e-39],
        [9.0000e-39, 1.0561e-38, 1.0653e-38],
        [4.1327e-39, 8.9082e-39, 9.8265e-39],
        [9.4592e-39, 1.0561e-38, 1.0653e-38],
        [1.0469e-38, 9.5510e-39, 9.1837e-39]])


In [3]:
# Construct a randomly initialized matrix:
# Returns a tensor filled with random numbers from a unifor distribution on the interval [0,1)
x = torch.rand(5,3)
print(x)

tensor([[0.1181, 0.0328, 0.3250],
        [0.0346, 0.3118, 0.7132],
        [0.9668, 0.0139, 0.3235],
        [0.4032, 0.4606, 0.4009],
        [0.6185, 0.9292, 0.8160]])


In [4]:
# Construct a matrix filled zeros and of dtype long:
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
# Construct a tensor directly from data:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [8]:
# or create a tensor based on an existing tensor. These methods will reuse 
# properties of the input tensor, e.g. dtype, unless new values are provided by user.
x = x.new_ones(5,3,dtype=torch.double) # new_* methods take in sizes
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [9]:
x = torch.randn_like(x, dtype=torch.float) # override dtype!
print(x)

tensor([[-0.7299,  0.4877,  0.7824],
        [-0.1230,  0.2678,  0.0411],
        [ 0.8467,  0.1289,  1.3538],
        [ 0.6413,  0.8935,  0.6386],
        [-1.2477,  0.1448,  0.1831]])


In [10]:
# Get its size:
# torch.Size is in fact a tuple, so it supports all tuple operations. 
print(x.size())

torch.Size([5, 3])


__Operations__

In [11]:
y = torch.rand(5,3)
print(x+y)

tensor([[-0.6299,  1.2472,  1.1079],
        [ 0.1570,  0.7821,  0.4032],
        [ 1.2160,  0.5495,  1.8527],
        [ 1.2471,  1.8558,  0.6774],
        [-0.9787,  0.6836,  0.7024]])


In [12]:
print(torch.add(x,y))

tensor([[-0.6299,  1.2472,  1.1079],
        [ 0.1570,  0.7821,  0.4032],
        [ 1.2160,  0.5495,  1.8527],
        [ 1.2471,  1.8558,  0.6774],
        [-0.9787,  0.6836,  0.7024]])


In [13]:
result = torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[-0.6299,  1.2472,  1.1079],
        [ 0.1570,  0.7821,  0.4032],
        [ 1.2160,  0.5495,  1.8527],
        [ 1.2471,  1.8558,  0.6774],
        [-0.9787,  0.6836,  0.7024]])


In [14]:
# Addition: in-place
y.add_(x)
print(y)

tensor([[-0.6299,  1.2472,  1.1079],
        [ 0.1570,  0.7821,  0.4032],
        [ 1.2160,  0.5495,  1.8527],
        [ 1.2471,  1.8558,  0.6774],
        [-0.9787,  0.6836,  0.7024]])


In [15]:
# Any operation that mutates a tensor in-place is post-fixed with an _. For example: 
# x.copy_(y), x.t_(), will change x.
print(x)

tensor([[-0.7299,  0.4877,  0.7824],
        [-0.1230,  0.2678,  0.0411],
        [ 0.8467,  0.1289,  1.3538],
        [ 0.6413,  0.8935,  0.6386],
        [-1.2477,  0.1448,  0.1831]])


In [17]:
print(x[:,1])

tensor([0.4877, 0.2678, 0.1289, 0.8935, 0.1448])


In [18]:
# Resizing：if you want to resize/reshape tensor, you can use `torch.view`:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8) 
# the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [19]:
# if you have a one element tensor, use `.item()` to get the value as Python number
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.3113])
0.3113322854042053


__Numpy Bridge__

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.   
The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other. 

In [20]:
# Converting a Torch Tensor to a Numpy Array
a = torch.ones(5)
print(a) 

tensor([1., 1., 1., 1., 1.])


In [21]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [22]:
# see how the numpy array changed in value.
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Coverting NumPy Array to Torch Tensor

In [23]:
# See how changing the np array changed the Torch Tensor automatically.
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to NumPy and back

__CUDA Tensors__

In [24]:
# Tensors can be moved onto any device using the `.to` method.

In [25]:
# Let us run this cell only if CUDA is available
# We will use "torch.device" objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda") # a CUDA device object
    y = torch.ones_like(x, device=device) # directly create a tensor on GPU
    x = x.to(device) # or just use strings ".to("cuda")"
    z = x + y
    print(z)